### ISSUE TITLE
BACKEND - Desenvolvimento do Ambiente 

### ISSUE THREAD

**Issue by MatheusSchimidt** [utfpr-pato-branco/scan-utfpr#20]
Desenvolver a estrutura dos ambientes (POST, GET, PUT, DELETE)

**Comment by MatheusSchimidt** [comment]
Em testes foi verificado que existiam dois erros:

- Na requisição PUT dos ambientes, não estava salvando o valor do campo "tamanhoBloco", porém esse erro foi corrigido e agora funciona perfeitamente.
- Nas requisições PUT e POST, adicionar uma validaçãona qual não permita informar o tamanho dos blocos zerados.

**Comment by reinaldohneto** [comment]
@MatheusSchimidt 

Realizada validações necessárias no put e post de Ambiente, já está em produção
